language: C++ 
compiler: g++

dist: xenial

script:
  - git ls-files src/ test/ | xargs clang-format -i && git diff --exit-code
script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
