language: C++ 
compiler: g++
# Используем дистрибутив Ubuntu 16.04,
# т.к. в образе предустановлен clang-format версии 7.

dist: xenial

script: git ls-files src/ thirdparty/ test/ | xargs clang-format -i && git diff --exit-code && src/ test/ thirdparty/